---
title: "Darwin Core mapping for fish tracking data"
author: "Peter Desmet"
date: "2017-05-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Transform data

```{r}
# Set libPaths.
.libPaths("/Users/peter_desmet/.exploratory/R/3.3")

# Load required packages.
library(janitor)
library(lubridate)
library(hms)
library(tidyr)
library(stringr)
library(readr)
library(forcats)
library(RcppRoll)
library(dplyr)
library(exploratory)

# Steps to produce the output
exploratory::read_delim_file("/Users/peter_desmet/Downloads/20170516_etn_sample_detections_view.csv" , ",", quote = "\"", skip = 0 , col_names = TRUE , na = c("","NA") , locale=locale(encoding = "UTF-8", decimal_mark = "."), trim_ws = FALSE , progress = FALSE) %>% exploratory::clean_data_frame() %>%
  arrange(transmitter, datetime) %>%
  mutate(occurrenceID = paste(transmitter, format(datetime, "%Y%m%d%H%M%S"), sep = ":")) %>%
  mutate(type = "Event") %>%
  mutate(language = "en") %>%
  mutate(license = "http://creativecommons.org/publicdomain/zero/1.0/") %>%
  mutate(rightsHolder = "INBO") %>%
  mutate(accessRights = "http://www.inbo.be/en/norms-for-data-use") %>%
  mutate(datasetID = "no DOI yet") %>%
  mutate(institutionCode = "INBO") %>%
  mutate(datasetName = "TODO") %>%
  mutate(basisOfRecord = "MachineObservation") %>%
  mutate(informationWithheld = "TODO") %>%
  mutate(dynamicProperties = paste("{\"receiver\":\"", receiver, "\", \"network_project_name\":\"", network_project_name, "\"}", sep = "")) %>%
  mutate(sex = "TODO") %>%
  mutate(lifeStage = "adult TODO") %>%
  mutate(organismID = transmitter) %>%
  mutate(samplingProtocol = "TODO") %>%
  mutate(samplingEffort = "TODO") %>%
  mutate(eventDate = format(datetime,"%Y-%m-%dT%H:%M:%SZ")) %>%
  mutate(locationID = station_name) %>%
  mutate(waterBody = "TODO maybe") %>%
  mutate(countryCode = "TODO maybe") %>%
  mutate(locality = location_name) %>%
  mutate(minimumDepthInMeters = "TODO") %>%
  mutate(decimalLatitude = sprintf("%.5f", round(latitude, digits = 5))) %>%
  mutate(decimalLongitude = sprintf("%.5f", round(longitude, digits = 5))) %>%
  mutate(geodeticDatum = "WGS84") %>%
  mutate(coordinateUncertaintyInMeters = "TODO") %>%
  mutate(georeferenceSources = "GPS") %>%
  mutate(georeferenceVerificationStatus = "TODO") %>%
  mutate(scientificName = scientific_name) %>%
  mutate(kingdom = "Animalia") %>%
  mutate(taxonRank = "species") %>%
  mutate(vernacularName = case_when(.$scientific_name == "Gadus morhua" ~ "Atlantic cod", .$scientific_name == "Anguilla anguilla" ~ "European eel")) %>%
  select(-X1, -receiver, -transmitter, -transmitter_name, -transmitter_serial, -sensor_value, -sensor_unit, -sensor2_value, -sensor2_unit, -station_name, -datetime, -id_pk, -qc_flag, -file, -latitude, -longitude, -deployment_fk, -scientific_name, -location_name, -deployment_station_name, -deploy_date_time, -animal_project, -animal_project_name, -animal_project_code, -animal_moratorium, -network_project, -network_project_name, -network_project_code, -network_moratorium, -signal_to_noise_ratio, -detection_file_id)
```
